### ISSUE TITLE
Windows new MediaInfoWrapper with valid fully qualified file name and path throws error

### ISSUE THREAD

**Issue by BermudaLamb** [yartat/MP-MediaInfo#47]
```
Value cannot be null.
Parameter name: logger
```
stack trace
```
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at MediaInfo.MediaInfoWrapper..ctor(String filePath, ILogger logger)
   at UserQuery.Fileinfo..ctor(String f) in xxx
```

**Comment by yartat** [comment]
Same to #44
